/** -------------------------------------------
 *  Field & Category configuration
 *  -------------------------------------------
 *  - Define precise field types, labels, options, and hints.
 *  - Any key not listed here will appear in "Others" with sensible defaults.
 */

import { CategoryConfig, FieldConfig } from "@/types/settings.type";

const GENERAL_FIELDS: FieldConfig[] = [
  {
    key: "site_name",
    label: "Site Name",
    type: "text",
    placeholder: "Findatable",
  },
  {
    key: "app_name",
    label: "App Name",
    type: "text",
    placeholder: "Findatable",
  },
  {
    key: "mode",
    label: "App Mode",
    type: "select",
    options: [
      { label: "Production", value: "production" },
      { label: "Staging", value: "staging" },
      { label: "Development", value: "development" },
    ],
  },
  {
    key: "logo",
    label: "App Logo URL",
    type: "file",
  },
  {
    key: "logo_dark",
    label: "App Dark Logo URL",
    type: "file",
  },
  {
    key: "about_us",
    label: "About Us",
    type: "textarea",
    rows: 4,
    placeholder: "Describe your app...",
  },
  {
    key: "language",
    label: "Default Language",
    type: "select",
    options: [
      { label: "English (en)", value: "en" },
      { label: "Dutch (nl)", value: "nl" },
      { label: "German (de)", value: "de" },
      { label: "French (fr)", value: "fr" },
    ],
    help: "Language used across the app by default.",
  },
  {
    key: "timezone",
    label: "Timezone",
    type: "text",
    placeholder: "Europe/Amsterdam",
  },
  {
    key: "currency",
    label: "Currency",
    type: "text",
    placeholder: "EUR",
  },
  {
    key: "currency_icon",
    label: "Currency Symbol",
    type: "text",
    placeholder: "€",
  },
  {
    key: "version_code_android",
    label: "Android Version Code",
    type: "text",
    placeholder: "1.0.0",
  },
  {
    key: "version_code_ios",
    label: "iOS Version Code",
    type: "text",
    placeholder: "1.0.0",
  },
];

const CONTACT_FIELDS: FieldConfig[] = [
  {
    key: "contact_address",
    label: "Contact Address",
    type: "textarea",
    rows: 3,
  },
  { key: "contact_email", label: "Contact Email", type: "email" },
  {
    key: "contact_phone",
    label: "Contact Phone",
    type: "text",
    placeholder: "+31...",
  },
  { key: "facebook", label: "Facebook URL", type: "url" },
  { key: "instagram", label: "Instagram URL", type: "url" },
  { key: "youtube", label: "YouTube URL", type: "url" },
  { key: "telegram", label: "Telegram URL", type: "url" },
  { key: "map_src", label: "Map Embed URL", type: "url" },
];

const URLS_FIELDS: FieldConfig[] = [
  { key: "privacy_policy", label: "Privacy Policy URL", type: "url" },
  { key: "terms_conditions", label: "Terms & Conditions URL", type: "url" },
  {
    key: "action_url",
    label: "Action URL",
    type: "url",
    help: "Used for in-app update / CTA.",
  },
  { key: "app_store_link", label: "App Store Link (iOS)", type: "url" },
  { key: "google_play_link", label: "Google Play Link (Android)", type: "url" },
  {
    key: "admin_dashboard_url",
    label: "Admin Dashboard URl",
    type: "url",
    placeholder: "enter url",
  },
  {
    key: "backend_url",
    label: "Backend URl",
    type: "url",
    placeholder: "enter url",
  },
  {
    key: "frontend_url",
    label: "Frontend URl",
    type: "url",
    placeholder: "enter url",
  },
  {
    key: "public_site_url",
    label: "Public Site URl",
    type: "url",
    placeholder: "enter url",
  },
  {
    key: "restaurant_admin_dashboard_url",
    label: "Restaurant Admin Dashboard URl",
    type: "url",
    placeholder: "enter url",
  },
  {
    key: "buttom_text",
    label: "Action Button Text",
    type: "text",
    placeholder: "Update Now",
  },
];

const RESERVATION_FIELDS: FieldConfig[] = [
  {
    key: "default_opening_time",
    label: "Opening Time",
    type: "time",
    placeholder: "09:00",
  },
  {
    key: "default_opening_time_hour",
    label: "Opening Hour",
    type: "hour",
    step: 1,
    min: 0,
    max: 23,
  },
  {
    key: "default_opening_time_minute",
    label: "Opening Minute",
    type: "minute",
    step: 1,
    min: 0,
    max: 59,
  },

  {
    key: "default_closing_time",
    label: "Closing Time",
    type: "time",
    placeholder: "21:00",
  },
  {
    key: "default_closing_time_hour",
    label: "Closing Hour",
    type: "hour",
    step: 1,
    min: 0,
    max: 23,
  },
  {
    key: "default_closing_time_minute",
    label: "Closing Minute",
    type: "minute",
    step: 1,
    min: 0,
    max: 59,
  },

  {
    key: "default_restaurant_capacity",
    label: "Default Restaurant Capacity",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "default_allow_walk_ins",
    label: "Allow Walk-ins by Default",
    type: "switch",
  },
  {
    key: "default_manual_booking_approval",
    label: "Manual Booking Approval by Default",
    type: "switch",
  },

  {
    key: "default_cancellation_policy_hours",
    label: "Cancellation Policy (hours)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "default_max_notice_days",
    label: "Max Notice (days)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "default_min_notice_minutes",
    label: "Min Notice (minutes)",
    type: "number",
    min: 0,
    step: 1,
  },

  {
    key: "max_party_size_for_automatic_confirmation",
    label: "Auto Confirm Up To (party size)",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: "max_reservation_editable_hours_after",
    label: "Editable Window After Reservation (hours)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "party_size_max",
    label: "Max Party Size",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: "slot_duration_hours",
    label: "Slot Duration (hours)",
    type: "number",
    min: 0,
    step: 0.25,
  },
  {
    key: "reservation_discount",
    label: "Reservation Discount (%)",
    type: "number",
    min: 0,
    max: 100,
    step: 1,
  },

  {
    key: "days_limit_for_editing_reservation",
    label: "Days Limit for Editing Reservation",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "days_limit_for_rating_reservation",
    label: "Days Limit for Rating Reservation",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "days_limit_for_replying_to_rating",
    label: "Days Limit for Replying to Rating",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "per_reservation_cost",
    label: "Per Reservation Cost",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "min_allowed_discount_percentage",
    label: "Min Allowed Discount (%)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 0",
  },
  {
    key: "max_allowed_discount_percentage",
    label: "Max Allowed Discount (%)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 100",
  },
  {
    key: "default_allocated_time_for_reservation_minutes",
    label: "Allocated Time for Reservation Minutes",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 90",
  },
  {
    key: "min_allowed_min_booking_notice_minutes",
    label: "Min Allowed Min Booking Notice (minutes)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 1440",
  },
  {
    key: "max_allowed_min_booking_notice_minutes",
    label: "Max Allowed Min Booking Notice (minutes)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 1440",
  },
];

const GIFT_CARDS: FieldConfig[] = [
  {
    key: "discount",
    label: "Gift Card Discount (%)",
    type: "number",
    min: 0,
    max: 100,
    step: 1,
    placeholder: "e.g. 10",
    help: "Percentage discount applied when purchasing a gift card (0–100%).",
  },
  {
    key: "tax",
    label: "Tax Rate (%)",
    type: "number",
    min: 0,
    max: 100,
    step: 0.1,
    placeholder: "e.g. 21",
    help: "VAT/Tax rate applied to gift card sales (0–100%).",
  },
  {
    key: "message_pricing",
    label: "Message Pricing",
    type: "number",
    min: 0,
    max: 100,
    step: 0.1,
    placeholder: "e.g. 2",
  },
  {
    key: "giftcard_validity_days",
    label: "Gift Card Validity (days)",
    type: "number",
    min: 0,
    max: 100,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "giftcard_validity_months",
    label: "Gift Card Validity (months)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 12",
  },
  {
    key: "giftcard_tax_percent",
    label: "Gift Card Tax (%)",
    type: "number",
    min: 0,
    max: 100,
    step: 0.1,
    placeholder: "e.g. 21",
  },
];

const LOYALTY_FIELDS: FieldConfig[] = [
  {
    key: "loyalty.account_signup",
    label: "Account Signup Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.reservation_completed",
    label: "Reservation Completed Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.review_published",
    label: "Review Published Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.restaurant_referral",
    label: "Restaurant Referral Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.user_referral",
    label: "User Referral Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.account_signup_with_referral_code",
    label: "Signup with Referral Code Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.voucher_generated",
    label: "Voucher Generated Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.voucher_used",
    label: "Voucher Used Points",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.point_deal_generated",
    label: "Point Deal Generated Points",
    type: "number",
    min: -100000,
    step: 1,
  },
  {
    key: "loyalty.minimum_redeem",
    label: "Minimum Redeem (pts)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.max_points_per_day",
    label: "Max Points per Day",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "loyalty.rewards_enabled",
    label: "Rewards Enabled",
    type: "switch",
  },
  {
    key: "loyalty.referrals_enabled",
    label: "Referrals Enabled",
    type: "switch",
  },
  {
    key: "redeemable_block",
    label: "Redeemable Block",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 12356",
  },
  {
    key: "amount_per_redemption",
    label: "Amount Per Redemption",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "voucher_validity_days",
    label: "Voucher Validity Day",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "point_deals_validity_days",
    label: "Point Deals Validity Day",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "eligible_sources_for_loyalty",
    label: "Eligible Sources",
    type: "select",
    options: [
      { label: "Platform", value: "platform" },
      { label: "Booking Widget", value: "booking_widget" },
    ],
  },
  {
    key: "restaurant_loyalty_share_per_redemption",
    label: "Restaurant Loyalty Share Per Redemption",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
];

const SECURITY_FIELDS: FieldConfig[] = [
  {
    key: "jwt_expiration_delta_hours",
    label: "JWT Expiration (hours)",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: "email_verification_token_expiry_hours",
    label: "Email Verification Token (hours)",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: "password_reset_token_expiry_hours",
    label: "Password Reset Token (hours)",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: "jwt_refresh_token_hours",
    label: "JWT Refresh Token (hours)",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 24",
  },
  {
    key: "jwt_remember_me_refresh_token_hours",
    label: "JWT Remember Me Refresh Token (hours)",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 720",
  },
  {
    key: "auth_max_failed_password_attempts",
    label: "Max Failed Password Attempts",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "auth_password_lockout_minutes",
    label: "Password Lockout (minutes)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 15",
  },
];
const INVOICE_FIELDS: FieldConfig[] = [
  {
    key: "subscription_payment_method",
    label: "Subscription Payment Method",
    type: "text",
    placeholder: "e.g. Credit Card, Bank Transfer",
  },
  {
    key: "platform_loyalty_share_per_redemption",
    label: "Platform Loyalty Share (Per Redemption)",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "platform_gift_card_comission_percent",
    label: "Platform Gift Card Commission (%)",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "tax_percent",
    label: "Tax Rate (%)",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 15",
  },
  {
    key: "per_cover_charge",
    label: "Per Cover Charge",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 3",
  },
  {
    key: "company_invoice_name",
    label: "Invoice Company Name",
    type: "text",
    placeholder: "e.g. Find A Table.",
  },
  {
    key: "company_invoice_address",
    label: "Invoice Address",
    type: "text",
    placeholder: "Street, City, Postal Code, Country",
  },
  {
    key: "company_chamber_of_commerce_number",
    label: "Chamber of Commerce Number",
    type: "text",
    placeholder: "e.g. 12345678",
  },
  {
    key: "company_vat_number",
    label: "VAT Number",
    type: "text",
    placeholder: "e.g. NL123456789B01",
  },
  {
    key: "company_iban_number",
    label: "IBAN Number",
    type: "text",
    placeholder: "e.g. NL91ABNA0417164300",
  },
  {
    key: "invoice_heading",
    label: "Invoice Heading",
    type: "text",
    placeholder: "e.g. Monthly Subscription Invoice",
  },
  {
    key: "tax_restaurant_invoice",
    label: "Tax Restaurant Invoice",
    type: "number",
    placeholder: "e.g. 15",
  },
  {
    key: "subscription_invoice_charge_delay_days",
    label: "Subscription Invoice Charge Delay (Days)",
    type: "number",
    placeholder: "Enter number of days before charging the invoice (e.g. 15)",
  },
  {
    key: "subscription_invoice_payment_max_attempts",
    label: "Subscription Maximum Invoice Payment Attempts",
    type: "number",
    placeholder: "Enter maximum retry attempts for invoice payment (e.g. 3)",
  },
  {
    key: "agreement_platform_signatory_name",
    label: "Agreement Platform Signatory Name",
    type: "text",
    placeholder: "e.g. John Doe",
  },
  {
    key: "agreement_platform_signatory_title",
    label: "Agreement Platform Signatory Title",
    type: "text",
    placeholder: "e.g. CEO",
  },
];
const Payment_FIELDS: FieldConfig[] = [
  {
    key: "stripe_connect_account_type",
    label: "Stripe Connect Account Type",
    type: "select",
    options: [{ label: "Express", value: "express" }],
  },
  {
    key: "stripe_connect_country",
    label: "Stripe Connect Country",
    type: "select",
    options: [
      { label: "Netherlands", value: "NL" },
      { label: "Belgium", value: "BE" },
      { label: "Germany", value: "DE" },
      { label: "France", value: "FR" },
      { label: "United Kingdom", value: "GB" },
      { label: "United States", value: "US" },
      { label: "Other", value: "OTHER" },
    ],
  },
  {
    key: "stripe_connect_return_url",
    label: "Stripe Connect Return Url",
    type: "url",
    placeholder: "e.g. https://yourapp.com/stripe/return",
  },
  {
    key: "stripe_connect_refresh_url",
    label: "Stripe Connect Refresh Url",
    type: "url",
    placeholder: "e.g. https://yourapp.com/stripe/refresh",
  },
  {
    key: "stripe_connect_reminder_days",
    label: "Stripe Connect Reminder Days",
    type: "number",
    placeholder: "e.g. 7",
  },
  {
    key: "weekly_payout_transfer_max_attempts",
    label: "Weekly Payout Transfer Max Attempts",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 3",
  },
  {
    key: "stripe_mode_staging",
    label: "Stripe Mode (Staging)",
    type: "select",
    options: [
      { label: "Test", value: "test" },
      { label: "Live", value: "live" },
    ],
  },
  {
    key: "stripe_mode_production",
    label: "Stripe Mode (Production)",
    type: "select",
    options: [
      { label: "Test", value: "test" },
      { label: "Live", value: "live" },
    ],
  },
];
const ONLINE_ORDER_FIELDS: FieldConfig[] = [
  {
    key: "online_order_service_charge",
    label: "Service Charge",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "pickup_service_fee_percentage",
    label: "Pickup Service Fee (%)",
    type: "number",
    min: 0,
    step: 0.1,
    placeholder: "e.g. 10",
  },
  {
    key: "delivery_service_fee_percentage",
    label: "Delivery Service Fee (%)",
    type: "number",
    min: 0,
    step: 0.1,
    placeholder: "e.g. 10",
  },
  {
    key: "default_preparation_buffer_minutes",
    label: "Preparation Buffer Minute",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "online_order_overload_created_grace_minutes",
    label: "Online Order Overload Created Grace Minutes",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
  {
    key: "max_orders_accepted",
    label: "Max Orders Accepted",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "online_order_transaction_fee",
    label: "Online Order Transaction Fee",
    type: "number",
    min: 0,
    step: 0.01,
    placeholder: "e.g. 0.30",
  },
  {
    key: "orders_prices_include_tax",
    label: "Order Prices Include Tax",
    type: "switch",
  },
  {
    key: "default_max_online_orders",
    label: "Default Max Online Orders",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 50",
  },
  {
    key: "default_online_order_overload_created_grace_minutes",
    label: "Default Online Order Overload Created Grace (minutes)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
];
const RESTAURANT_RESOURCE_FIELDS: FieldConfig[] = [
  {
    key: "max_restaurant_amenities",
    label: "Max Restaurant Amenities",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_restaurant_cuisines",
    label: "Max Restaurant Cuisines",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_restaurant_delivery_zones",
    label: "Max Restaurant Delivery Zones",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_restaurant_features",
    label: "Max Restaurant Features",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_restaurant_primary_images",
    label: "Max Restaurant Primary Images",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_restaurant_social_links",
    label: "Max Restaurant Social Links",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_restaurant_verification_files",
    label: "Max Restaurant Verification Files",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "max_request_size_mb",
    label: "Max Request Size (MB)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 50",
  },
];
const REVIEWS_FIELDS: FieldConfig[] = [
  {
    key: "max_time_allowed_till_rating_can_be_edited_by_customer_days",
    label: "Maximum Days to Edit Rating by Customer",
    type: "number",
    min: 0,
    step: 1,
    placeholder:
      "Enter number of days a customer can edit their rating (e.g. 30)",
  },
  {
    key: "max_allowed_rating_update_counts_for_customer",
    label: "Maximum Rating Update Counts for Customer",
    type: "number",
    min: 0,
    step: 1,
    placeholder:
      "Enter how many times a customer can update their rating (e.g. 3)",
  },
];
const EMAIL_FIELDS: FieldConfig[] = [
  {
    key: "info_from_email",
    label: "Info From Email",
    type: "email",
    placeholder: "info@findatable.nl",
  },
  {
    key: "giftcards_from_email",
    label: "Gift Cards From Email",
    type: "email",
    placeholder: "giftcards@findatable.nl",
  },
  {
    key: "customers_from_email",
    label: "Customers From Email",
    type: "email",
    placeholder: "customers@findatable.nl",
  },
  {
    key: "support_from_email",
    label: "Support From Email",
    type: "email",
    placeholder: "support@findatable.nl",
  },
  {
    key: "finance_from_email",
    label: "Finance From Email",
    type: "email",
    placeholder: "finance@findatable.nl",
  },
  {
    key: "privacy_from_email",
    label: "Privacy From Email",
    type: "email",
    placeholder: "privacy@findatable.nl",
  },
  {
    key: "partners_from_email",
    label: "Partners From Email",
    type: "email",
    placeholder: "partners@findatable.nl",
  },
  {
    key: "sales_from_email",
    label: "Sales From Email",
    type: "email",
    placeholder: "sales@findatable.nl",
  },
  {
    key: "billing_from_email",
    label: "Billing From Email",
    type: "email",
    placeholder: "billing@findatable.nl",
  },
  {
    key: "salary_from_email",
    label: "Salary From Email",
    type: "email",
    placeholder: "salary@findatable.nl",
  },
  {
    key: "restaurant_from_email",
    label: "Restaurant From Email",
    type: "email",
    placeholder: "partners@findatable.nl",
  },
  {
    key: "giftcard_from_email",
    label: "Gift Card From Email",
    type: "email",
    placeholder: "giftcards@findatable.nl",
  },
  {
    key: "reservation_from_email",
    label: "Reservation From Email",
    type: "email",
    placeholder: "reservations@findatable.nl",
  },
  {
    key: "reservations_from_email",
    label: "Reservations From Email",
    type: "email",
    placeholder: "reservations@findatable.nl",
  },
  {
    key: "orders_from_email",
    label: "Orders From Email",
    type: "email",
    placeholder: "orders@findatable.nl",
  },
];

const LOCATION_GEOCODING_FIELDS: FieldConfig[] = [
  {
    key: "location_geocode_primary_provider",
    label: "Geocode Primary Provider",
    type: "select",
    options: [
      { label: "PDOK", value: "pdok" },
      { label: "Nominatim", value: "nominatim" },
      { label: "Google", value: "google" },
    ],
  },
  {
    key: "location_geocode_fallback_provider",
    label: "Geocode Fallback Provider",
    type: "select",
    options: [
      { label: "PDOK", value: "pdok" },
      { label: "Nominatim", value: "nominatim" },
      { label: "Google", value: "google" },
    ],
  },
  {
    key: "location_provider_enable_fallback",
    label: "Enable Provider Fallback",
    type: "switch",
  },
  {
    key: "location_geocode_timeout_seconds",
    label: "Geocode Timeout (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "location_geocode_success_ttl_seconds",
    label: "Geocode Success TTL (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 86400",
  },
  {
    key: "location_geocode_not_found_ttl_seconds",
    label: "Geocode Not-Found TTL (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 600",
  },
  {
    key: "location_geocode_error_ttl_seconds",
    label: "Geocode Error TTL (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
  {
    key: "location_pdok_base_url",
    label: "PDOK Base URL",
    type: "url",
    placeholder: "https://api.pdok.nl/...",
  },
  {
    key: "location_pdok_suggest_url",
    label: "PDOK Suggest URL",
    type: "url",
    placeholder: "https://api.pdok.nl/locatieserver/v3/suggest",
  },
  {
    key: "location_pdok_reverse_url",
    label: "PDOK Reverse URL",
    type: "url",
    placeholder: "https://api.pdok.nl/locatieserver/v3/reverse",
  },
  {
    key: "location_pdok_rows",
    label: "PDOK Rows",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "location_search_default_limit",
    label: "Search Default Limit",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "location_search_success_ttl_seconds",
    label: "Search Success TTL (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 3600",
  },
  {
    key: "location_search_not_found_ttl_seconds",
    label: "Search Not-Found TTL (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 600",
  },
  {
    key: "location_search_error_ttl_seconds",
    label: "Search Error TTL (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
  {
    key: "location_rate_limit_geocode",
    label: "Rate Limit: Geocode",
    type: "text",
    placeholder: "e.g. 60/minute",
  },
  {
    key: "location_rate_limit_autocomplete",
    label: "Rate Limit: Autocomplete",
    type: "text",
    placeholder: "e.g. 120/minute",
  },
  {
    key: "location_rate_limit_search",
    label: "Rate Limit: Search",
    type: "text",
    placeholder: "e.g. 60/minute",
  },
  {
    key: "location_rate_limit_reverse",
    label: "Rate Limit: Reverse",
    type: "text",
    placeholder: "e.g. 60/minute",
  },
  {
    key: "location_rate_limit_address_lookup",
    label: "Rate Limit: Address Lookup",
    type: "text",
    placeholder: "e.g. 60/minute",
  },
  {
    key: "location_pdok_filter_query",
    label: "PDOK Filter Query",
    type: "text",
    placeholder: "e.g. type:adres",
  },
  {
    key: "location_nominatim_user_agent",
    label: "Nominatim User Agent",
    type: "text",
    placeholder: "e.g. findatable/1.0 (contact@findatable.nl)",
  },
];

const BOOKING_WIDGET_FIELDS: FieldConfig[] = [
  {
    key: "widget_cover_fee",
    label: "Widget Cover Fee",
    type: "number",
    min: 0,
    step: 0.01,
    placeholder: "e.g. 1.50",
  },
  {
    key: "widget_verification_enabled",
    label: "Widget Verification Enabled",
    type: "switch",
  },
  {
    key: "widget_verification_token_expiry_minutes",
    label: "Widget Verification Token Expiry (minutes)",
    type: "number",
    min: 1,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "widget_verification_resend_cooldown_seconds",
    label: "Widget Verification Resend Cooldown (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
  {
    key: "widget_fraud_max_reservations_per_email_per_hour",
    label: "Max Reservations per Email per Hour",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "widget_fraud_max_reservations_per_ip_per_hour",
    label: "Max Reservations per IP per Hour",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "widget_fraud_max_same_slot_per_email_per_day",
    label: "Max Same Slot per Email per Day",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 2",
  },
  {
    key: "widget_fraud_min_seconds_between_submissions",
    label: "Min Seconds Between Submissions",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "widget_fraud_block_missing_user_agent",
    label: "Block Missing User Agent",
    type: "switch",
  },
];

const AGREEMENTS_SIGNATURE_FIELDS: FieldConfig[] = [
  {
    key: "agreement_acceptor_signature_enabled",
    label: "Acceptor Signature Enabled",
    type: "switch",
  },
  {
    key: "agreement_platform_signature_image_url",
    label: "Platform Signature Image URL",
    type: "file",
  },
];

const DATA_EXPORT_PRIVACY_FIELDS: FieldConfig[] = [
  {
    key: "data_export_max_requests_per_day",
    label: "Max Export Requests per Day",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 3",
  },
  {
    key: "data_export_request_cooldown_minutes",
    label: "Export Request Cooldown (minutes)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
  {
    key: "data_export_max_active_requests_per_user",
    label: "Max Active Requests per User",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 2",
  },
  {
    key: "data_export_download_token_ttl_minutes",
    label: "Download Token TTL (minutes)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "data_export_cleanup_batch_size",
    label: "Cleanup Batch Size",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 100",
  },
];

const COOKIE_CONSENT_FIELDS: FieldConfig[] = [
  {
    key: "cookie_consent_banner_enabled",
    label: "Cookie Consent Banner Enabled",
    type: "switch",
  },
  {
    key: "cookie_consent_require_opt_in_for_analytics",
    label: "Require Opt-in for Analytics",
    type: "switch",
  },
  {
    key: "cookie_consent_require_opt_in_for_marketing",
    label: "Require Opt-in for Marketing",
    type: "switch",
  },
  {
    key: "cookie_policy_current_version",
    label: "Cookie Policy Current Version",
    type: "text",
    placeholder: "e.g. 2024-01-01",
  },
  {
    key: "cookie_policy_url",
    label: "Cookie Policy URL",
    type: "url",
    placeholder: "https://findatable.nl/cookies",
  },
  {
    key: "cookie_policy_reconsent_on_version_change",
    label: "Re-consent on Version Change",
    type: "switch",
  },
  {
    key: "cookie_consent_max_age_days",
    label: "Cookie Consent Max Age (days)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 365",
  },
];

const ADVANCED_TENANCY_FIELDS: FieldConfig[] = [
  {
    key: "NEAR_ME_RADIUS_KM",
    label: "Near Me Radius (km)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
  {
    key: "discount_enabled",
    label: "Discount Enabled",
    type: "switch",
  },
  {
    key: "restaurant_profile_incomplete_min_age_days",
    label: "Restaurant Profile Incomplete Min Age (days)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 7",
  },
  {
    key: "eligible_sources_for_discount",
    label: "Eligible Sources for Discount",
    type: "tags",
    placeholder: "Add source and press Enter",
  },
  {
    key: "loyalty_transaction_actions_affected_by_source_of_reservation",
    label: "Loyalty Actions Affected by Reservation Source",
    type: "tags",
    placeholder: "Add action and press Enter",
  },
  {
    key: "featured_tag_slugs",
    label: "Featured Tag Slugs",
    type: "tags",
    placeholder: "Add slug and press Enter",
  },
];

const MENU_IMPORT_FIELDS: FieldConfig[] = [
  {
    key: "menu_single_sheet_import_max_file_size_mb",
    label: "Max File Size (MB)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "menu_single_sheet_import_max_rows",
    label: "Max Rows",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 1000",
  },
  {
    key: "menu_single_sheet_import_min_interval_seconds",
    label: "Min Interval Between Imports (seconds)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 60",
  },
  {
    key: "menu_single_sheet_import_max_requests_per_hour",
    label: "Max Requests per Hour",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 10",
  },
];

const OTHER_FIELDS: FieldConfig[] = [
  {
    key: "default_country",
    label: "Default Country",
    type: "select",
    options: [
      { label: "Netherlands", value: "Netherlands" },
      { label: "Belgium", value: "Belgium" },
      { label: "Germany", value: "Germany" },
      { label: "France", value: "France" },
      { label: "United Kingdom", value: "United Kingdom" },
      { label: "United States", value: "United States" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    key: "default_restaurant_status",
    label: "Default Restaurant Status",
    type: "select",
    options: [
      { label: "Pending Approval", value: "pending_approval" },
      { label: "Approved", value: "approved" },
      { label: "Disabled", value: "disabled" },
    ],
  },
  {
    key: "force_update",
    label: "Force App Update",
    type: "switch",
    help: "When enabled, users are required to update before proceeding.",
  },
  {
    key: "maintenance_date_time",
    label: "Maintenance Date Time",
    type: "datetime-local",
    min: new Date().toISOString().slice(0, 16),
  },
  {
    key: "maintenance_description",
    label: "Maintenance Description",
    type: "textarea",
    rows: 4,
    placeholder: "Enter maintenance description..",
  },
  {
    key: "maintenance_mode",
    label: "Maintenance Mode",
    type: "switch",
  },
  {
    key: "device_activation_expire",
    label: "Device Activation Expire",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "comparision_list_limit",
    label: "Comparison List Limit",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "near_me_radius_km",
    label: "Near Me Radius (km)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "recently_joined_restaurant_count_in_home_page",
    label: "Recently Joined Restaurant Count (home page)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "top_rated_restaurant_count_in_home_page",
    label: "Top Rated Restaurant Count (home page)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "top_reserved_restaurant_count_in_home_page",
    label: "Top Reserved Restaurant Count (home page)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "top_trending_restaurant_count_in_home_page",
    label: "Top Trending Restaurant Count (home page)",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "default_page_size",
    label: "Default Page Size",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "max_page_size",
    label: "Max Page Size",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "trend_window_days",
    label: "Trend Window Days",
    type: "number",
    min: 0,
    step: 1,
  },
  {
    key: "trend_score_rating_weight",
    label: "Trend Score Rating Weight",
    type: "number",
    min: 0,
    step: 0.1,
    placeholder: "e.g. 0.7",
  },
  {
    key: "trend_score_rating_count_weight",
    label: "Trend Score Rating Count Weight",
    type: "number",
    min: 0,
    step: 0.1,
    placeholder: "e.g. 0.7",
  },
  {
    key: "trend_score_reservation_weight",
    label: "Trend Score Reservation Weight",
    type: "number",
    min: 0,
    step: 0.1,
    placeholder: "e.g. 0.7",
  },
  {
    key: "plan_change_request_effective_days",
    label: "Plan Change Request Effective Days",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 30",
  },
  {
    key: "support_email",
    label: "Support Email",
    type: "email",
    placeholder: "e.g. example@demo.com",
  },
  {
    key: "max_upload_size_mb",
    label: "Max File Size (MB)",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "max_files_per_request",
    label: "Max File Count Per Request",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
  {
    key: "max_restaurant_dietary_options",
    label: "Max Restaurant Dietary Options",
    type: "number",
    min: 0,
    step: 1,
    placeholder: "e.g. 5",
  },
];

const mobileAppFields = (prefix: string): FieldConfig[] => [
  {
    key: `${prefix}.app_store_link`,
    label: "App Store Link (iOS)",
    type: "url",
  },
  {
    key: `${prefix}.google_play_link`,
    label: "Google Play Link (Android)",
    type: "url",
  },
  {
    key: `${prefix}.version_code_android`,
    label: "Android Version Code",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: `${prefix}.version_code_ios`,
    label: "iOS Version Code",
    type: "number",
    min: 1,
    step: 1,
  },
  {
    key: `${prefix}.force_update`,
    label: "Force Update",
    type: "switch",
  },
  {
    key: `${prefix}.action_url`,
    label: "Update Action URL",
    type: "url",
  },
  {
    key: `${prefix}.buttom_text`,
    label: "Update Button Text",
    type: "text",
    placeholder: "Update App",
  },
];

export const CATEGORIES: Record<string, CategoryConfig> = {
  general: {
    label: "General",
    description: "Basic app identity & locale settings.",
    fields: GENERAL_FIELDS,
  },
  contact: {
    label: "Contact & Social",
    description: "Company contacts and social links.",
    fields: CONTACT_FIELDS,
  },
  urls: {
    label: "URLs & Policies",
    description: "Legal pages and app-related URLs.",
    fields: URLS_FIELDS,
  },
  reservations: {
    label: "Reservations",
    description: "Reservation defaults and limits.",
    fields: RESERVATION_FIELDS,
  },
  giftCards: {
    label: "Gift Cards",
    description: "Gift card pricing and tax settings.",
    fields: GIFT_CARDS,
  },
  loyalty: {
    label: "Loyalty Points",
    description: "Configure earn actions and redemption rules.",
    fields: LOYALTY_FIELDS,
  },
  security: {
    label: "Security",
    description: "Token lifetimes and security timeouts.",
    fields: SECURITY_FIELDS,
  },
  invoice: {
    label: "Invoice",
    description: "Invoice configurations.",
    fields: INVOICE_FIELDS,
  },
  payment: {
    label: "Payment",
    description: "Payment configurations.",
    fields: Payment_FIELDS,
  },
  online_order: {
    label: "Online Order",
    description: "Online order configurations.",
    fields: ONLINE_ORDER_FIELDS,
  },
  reviews: {
    label: "Reviews",
    description: "Reviews configurations.",
    fields: REVIEWS_FIELDS,
  },
  restaurantResource: {
    label: "Restaurant Resource Limit",
    description: "Restaurant Resource Limit configurations.",
    fields: RESTAURANT_RESOURCE_FIELDS,
  },
  mobileApps: {
    label: "Manage All Applications",
    description:
      "Customer, Restaurant Manager, and POS mobile application settings.",
    fields: [],
    subCategories: {
      customer_mobile_app: {
        label: "Customer App",
        description: "Customer mobile application settings.",
        fields: mobileAppFields("customer_mobile_app_settings"),
      },
      restaurant_manager_mobile_app: {
        label: "Restaurant Manager App",
        description: "Restaurant manager mobile app settings.",
        fields: mobileAppFields("restaurant_manager_mobile_app_settings"),
      },
      pos_mobile_app: {
        label: "POS App",
        description: "POS mobile application settings.",
        fields: mobileAppFields("pos_mobile_app_settings"),
      },
    },
  },
  emails: {
    label: "Emails",
    description: "System email sender configurations.",
    fields: EMAIL_FIELDS,
  },
  locationGeocoding: {
    label: "Location & Geocoding",
    description: "Geocoding providers, caching TTLs and rate limits.",
    fields: LOCATION_GEOCODING_FIELDS,
  },
  bookingWidget: {
    label: "Booking Widget",
    description: "Booking widget verification and anti-fraud configuration.",
    fields: BOOKING_WIDGET_FIELDS,
  },
  agreementsSignature: {
    label: "Agreements & Signature",
    description: "Agreement and signature configuration.",
    fields: AGREEMENTS_SIGNATURE_FIELDS,
  },
  dataExportPrivacy: {
    label: "Data Export & Privacy",
    description: "DSAR / data export limits and lifetimes.",
    fields: DATA_EXPORT_PRIVACY_FIELDS,
  },
  cookieConsent: {
    label: "Cookie Consent",
    description: "Cookie banner, policy versioning and consent rules.",
    fields: COOKIE_CONSENT_FIELDS,
  },
  advancedTenancy: {
    label: "Advanced / Tenancy & Discovery",
    description: "Discovery, discount sources and feature flagging.",
    fields: ADVANCED_TENANCY_FIELDS,
  },
  menuImport: {
    label: "Menu Import",
    description: "Single-sheet menu import limits.",
    fields: MENU_IMPORT_FIELDS,
  },
  platform: {
    label: "Others",
    description: "Platform defaults and enforcement flags.",
    fields: OTHER_FIELDS,
  },
};
